# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concursos',
            fields=[
                ('concurso', models.IntegerField(primary_key=True, serialize=False)),
                ('dezena1', models.CharField(max_length=2)),
                ('dezena2', models.CharField(max_length=2)),
                ('dezena3', models.CharField(max_length=2)),
                ('dezena4', models.CharField(max_length=2)),
                ('dezena5', models.CharField(max_length=2)),
                ('dezena6', models.CharField(max_length=2)),
            ],
        ),
    ]
