# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursos',
            name='acumulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concursos',
            name='acumulado_mega_virada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='arr_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='cidade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 6, 3, 0, 26, 39, 23034)),
        ),
        migrations.AddField(
            model_name='concursos',
            name='est_premio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='gan_quadra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='gan_quina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='gan_sena',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='rat_quadra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='rat_quina',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='rat_sena',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='uf',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='concursos',
            name='val_acumulado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
