# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0002_auto_20160603_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concursos',
            name='acumulado',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='concursos',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 6, 3, 0, 29, 49, 617593)),
        ),
    ]
